version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_EXECUTABLE_PATH: "server/target/server-1.0-SNAPSHOT.jar"
    ports: 
      - 8081:8081
    networks:
      - zerocopy-test-net
    volumes:
      - zerocopy-test-vol:/data
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_EXECUTABLE_PATH: "client/target/client-1.0-SNAPSHOT.jar"
    ports: 
      - 8080:8080
    networks:
      - zerocopy-test-net
    depends_on:
      - server
volumes:
  zerocopy-test-vol:
    driver: local
networks:
  zerocopy-test-net:
    
    
    
